### ISSUE TITLE
RSI documentation unclear

### ISSUE THREAD

**Issue by mpolicki** [DaveSkender/Stock.Indicators#1225]
### What happened?

The [RSI documentation page](https://dotnet.stockindicators.dev/indicators/Rsi/#content), under the heading _Historical quotes requirements_, says:
> You must have at least N+100 periods of quotes to cover the convergence periods. Since this uses a smoothing technique, we recommend you use at least 10×N data points prior to the intended usage date for better precision.

I find this confusing. Do I need N+100 data points or 10×N data points? Or `Math.Max(N+100, 10×N)`?

Furthermore, are those data points to be used exclusively for warmup? In other words, do I need to add N more data points on top of that?

**Comment by mpolicki** [comment]
After a bit of thinking, I've had an idea. It's good to have this information in the documentation, but it would be even better to also have it in the code. That is, it would be nice for every indicator to have a function which returns the number of warmup periods necessary for reasonable accuracy.

**Comment by DaveSkender** [comment]
I suspect you're trying to determine _what is the minimum amount of historical quotes I need_ to calculate a single good RSI value?  I'll explain more below; however, for indicators like RSI that converge to better accuracy over time, using the minimum amount of quote history as possible _is NOT a good way to optimize_ your system.

### What RSI docs say right now

> ### Historical quotes requirements
> 
> You must have at least `N+100` periods of `quotes` to cover the convergence periods.  Since this uses a smoothing technique, we recommend you use at least `10×N` data points prior to the intended usage date for better precision.
> 
> `quotes` is a collection of generic `TQuote` historical price quotes.  It should have a consistent frequency (day, hour, minute, etc).  See [the Guide](https://dotnet.stockindicators.dev/guide/#historical-quotes) for more information.
> 
> ## Response
> 
> ```csharp
> IEnumerable<RsiResult>
> ```
> 
> - This method returns a time series of all available indicator values for the `quotes` provided.
> - It always returns the same number of elements as there are in the historical quotes.
> - It does not return a single incremental indicator value.
> - The first `N-1` periods will have `null` values since there's not enough data to calculate.
> 
> >&#9886; **Convergence warning**: The first `10×N` periods will have decreasing magnitude, convergence-related precision errors that can be as high as ~5% deviation in indicator values for earlier periods.

#### How to read and interpret it

The explanation here is saying that the first `N+100` periods are not recommended for use because they contain noticeably incorrect values.  For most use cases, these are a minimally sufficient amount to avoid.  If you want maximum accuracy to even more decimal points, use the higher value of `10×N`.  Here's what using different amounts of preceding history looks like to RSI(14):

```bash
RSI(14) on 09/04/2020 with    5 periods: (incalculable)
RSI(14) on 09/04/2020 with   14 periods: (incalculable)
RSI(14) on 09/04/2020 with   28 periods: 54.74661765 <<- noticeably inaccurate
RSI(14) on 09/04/2020 with   40 periods: 54.06326291 
RSI(14) on 09/04/2020 with   50 periods: 54.47116982
RSI(14) on 09/04/2020 with   75 periods: 53.48907880
RSI(14) on 09/04/2020 with  100 periods: 53.37715995
RSI(14) on 09/04/2020 with  110 periods: 53.40465210
RSI(14) on 09/04/2020 with  120 periods: 53.38950926 <<- reasonably accurate
RSI(14) on 09/04/2020 with  130 periods: 53.36611841
RSI(14) on 09/04/2020 with  140 periods: 53.37220833
RSI(14) on 09/04/2020 with  150 periods: 53.37528522 <<- fully converged to 3 decimal points
RSI(14) on 09/04/2020 with  160 periods: 53.37506203
RSI(14) on 09/04/2020 with  175 periods: 53.37518141
RSI(14) on 09/04/2020 with  200 periods: 53.37519202
RSI(14) on 09/04/2020 with  250 periods: 53.37519303
RSI(14) on 09/04/2020 with  350 periods: 53.37519313 <<- fully converged to 8 decimal points
RSI(14) on 09/04/2020 with  500 periods: 53.37519313
RSI(14) on 09/04/2020 with  600 periods: 53.37519313
RSI(14) on 09/04/2020 with  700 periods: 53.37519313
RSI(14) on 09/04/2020 with  800 periods: 53.37519313
RSI(14) on 09/04/2020 with  900 periods: 53.37519313
RSI(14) on 09/04/2020 with 1000 periods: 53.37519313
```

### Answer your questions

> Do I need N+100 data points or 10×N data points? Or Math.Max(N+100, 10×N)?

If you want the last value in your results to be _reasonably accurate_, use `N+100` (good).  If you want more accuracy, use `10×N` (better).  From the analysis above, you can go further to at least `25×N` (best).  The results before this point are the _warmup periods_ that are less accurate.  Exactly how much precision you need will depend on your use case and personal tolerance.

For most charting applications, "good" is enough for RSI; however, since these methods calculate entire series of results, aiming for the last value to be "good" is unusual.

> Are those data points to be used exclusively for warmup? In other words, do I need to add N more data points on top of that?

Yes.  Anything within the warmup periods is less accurate and is typically _ignored and not used_ and subsequent analysis or visualizations.  For example, if I wanted to show RSI(`N`), where `N` is the `lookbackPeriods`, over the last year on a chart with daily quotes (250 days), I'd want to use `250 + 10×N` historical quotes to calculate RSI, so the last 250 points shown are at least "better" precision.

> After a bit of thinking, I've had an idea. It's good to have this information in the documentation, but it would be even better to also have it in the code. That is, it would be nice for every indicator to have a function which returns the number of warmup periods necessary for reasonable accuracy.

A long time ago, we had been throwing an exception when people didn't provide enough historical quotes, but that ended up creating even more friction since everyone had a different idea of where that threshold should exist, many not wanting it at all.  Now, we just document and provide some utilities to help out.

### More info

- the guide: [how much historical quote data do I need?](https://dotnet.stockindicators.dev/guide/#historical-quotes)
- expanded discussion on [warmup and convergence](https://github.com/DaveSkender/Stock.Indicators/discussions/688)
- #656 (why we stopped validating quote history length)

**Comment by DaveSkender** [comment]
I've had a general indicator reference utility in the backlog for a while, so I'll add this recommendation to include _minimum quote values_ in it.

While this may be useful for checking whether to even attempt an indicator where more quote history is simply not available (e.g. a new ticker symbol), generally optimizing for use of _minimum quote history_ is probably not a great idea overall since you'll always be working somewhere in the _less accurate zone_ of results.

**Comment by mpolicki** [comment]
First of all, thank you for the extensive answer (and furthermore, thank you for all the work on this excellent library).

> I suspect you're trying to determine what is the minimum amount of historical quotes I need to calculate a single good RSI value?

Indeed.

> For indicators like RSI that converge to better accuracy over time, using the minimum amount of quote history as possible is NOT a good way to optimize your system.

I realize you want to steer people away from getting insufficiently accurate results, but use cases are different. Mine doesn't even require tenths, for example. I'm also wary of bloating my database file or requesting too much data from the exchange, which might get me rate-limited or even IP-banned.

> If you want the last value in your results to be reasonably accurate, use N+100 (good). If you want more accuracy, use 10×N (better).

The problem with this is that N+100 > 10×N for N < 12. In other words, for N <= 11, this advice says less data points is better :)

> Now, we just document and provide some utilities to help out.

I have a feeling that at least some of the people using this library who aren't already well-versed in technical analysis math look at the documentation for an indicator and translate the part about historical quote requirements into a bit of code. In any case, that's what I did. And since it's redundant for everyone to do that same thing for themselves, I suggested that the library itself provide that bit of code.

I do, however, realize that "reasonable" is subjective and what you determine to be reasonable accuracy would not be sufficient for some people. So it seems to me that the best solution could be to have a function per indicator that takes as input the number of accurate/converged significant digits the user wants, and outputs the number of warm-up data points needed. What do you think?

**Comment by DaveSkender** [comment]
I just [calculate a bunch of samples](https://github.com/DaveSkender/Stock.Indicators/blob/62a0e862cb3ed4ce28a4928b3cffdf61919e6681/tests/other/Convergence.Tests.cs) using different indicator parameters to get a sense of _typical_ scenarios, and provide a simple rule of thumb.  For RSI, larger `N` values fit better to the 10x, while smaller ones fit better to `N+100`

Actual convergence will also vary a lot when prices are volatile, so _the precise definition you’re seeking_ would have to be a notably _more confusing complex mathematical equation_ that’d not be so easy to use (or define).

If you want to explore this further, I’m game.  Sounds like fun math problems to solve, but I’d recommend starting a [new discussion thread](https://github.com/DaveSkender/Stock.Indicators/discussions) for it.
