### ISSUE TITLE
is issue #949 really fixed?

### ISSUE THREAD

**Issue by mihakralj** [DaveSkender/Stock.Indicators#1263]
### What happened?

Seems like initial value for TR (True Range) is still zero. When the loop starts, your code sets the prevClose to the current close and then skips the TR calculation entirely (due to the continue statement)

This means that in your implementation, the TR for the first bar is effectively left as 0 and even the initial ATR average is calculated from the second bar onwards. I thought this was fixed in #949? Going through commit code, changes that were implemented in #949 are not in the main branch now.

the xlst test for True Range is also skipping the first bar. This is contrary to official Wilder's definition of TR and ATR: https://user-images.githubusercontent.com/31756078/163031211-e3b8b4c7-b453-464a-b561-44171ca2b89e.png

**Comment by DaveSkender** [comment]
v2.5.0 published on 11/15/2022 and this was merged on 11/26 … it’s never been deployed!

**Comment by DaveSkender** [comment]
I’ve redeployed a new version, but now see that these merged on 11/26/**2022**.  These changes have been available since 2.4.1.

I thing we resolved some of Wilder’s inconsistencies here:

- #947 and fixed in
- #949

**Comment by mihakralj** [comment]
Here is what I see on main branch in [Atr.Series.cs](https://github.com/DaveSkender/Stock.Indicators/blob/main/src/a-d/Atr/Atr.Series.cs):

```
            if (i > 0)
            {
                hmpc = Math.Abs(q.High - prevClose);
                lmpc = Math.Abs(q.Low - prevClose);
            }
            else
            {
                prevClose = q.Close;
                continue;
            }
```

The `else` clause is incomplete - it doesn't define tr (as `q.High-q.Low`) when i=0 - and continues into the second loop (i=1)

I did think we resolved it, but clearly the first Tr calculated in your code is 0 instead of high-low...

**Comment by DaveSkender** [comment]
Yes, that is the actual fix.  The old uncorrected version used to set TR as `q.High-q.Low` when `i=0`.  Reading down through Wilder’s docs, he uses this “guess” value to initialize inconsistently, so it’s difficult to say which is better by purely relying on his notes.  I think he actually made a mistake, the guess value isn’t mathematically consistent, so we just skip the first period.

**Comment by DaveSkender** [comment]
@mihakralj are you satisfied here?  I’d like to close this one.

**Comment by mihakralj** [comment]
well, if the code snippet above is as you like it - exiting the loop without actually defining the first tr, then let's close the issue as 'by design'. I will diverge from your interpretation and set the first tr value as `tr = q.High-q.Low` 

Your interpretation and mine have a different starting point (your first `tr=0` and mine `tr=High-Low`) - but they converge and become the same.

Just like starting ema() with zero instead using the first value as a seed. It might be incorrect at the beginning, but will converge to a conventional ema.

Feel free to close the issue and keep the code as-is.

**Comment by DaveSkender** [comment]
**This does fall into the _dealer's choice_ category.**  I tend to bias towards _excluding incalculable periods_ -- ones that deviate from the normal _accurate_ steady-state formula.  I flex on this bias a bit for long-lead converging types, but True Range (TR) isn't a converging type.

I see [you initially really wanted](https://github.com/DaveSkender/Stock.Indicators/issues/947#issuecomment-1325996365) to go with `TR[0]=High[0]-Low[0]` back when we looked at this a couple years ago.  Based on that prior conversation, I'd made a tweak that [arrived at some consensus](https://github.com/mihakralj/QuanTAlib/issues/12#issuecomment-1331603135).

![](https://github.com/user-attachments/assets/a0ed6795-6950-4bb9-9792-f6466676985a)

[That tweak](https://github.com/DaveSkender/Stock.Indicators/pull/949/files#diff-6387c6c9a9430b7f475b3131c79181683b2f3a8534b3c97b9e976610e80cd64aR22-R26) actually removed the use of `High[0]-Low[0]` as the initializer.  Since I leaned on my bias and decided to not return the first period, I could calculate `Tr[1]` normally (_accurately_).

<img width="422" alt="image" src="https://github.com/user-attachments/assets/a828ece8-24ea-4f79-b8f5-c38c441fc9c5">

I still think [Wilder probably made a mistake](https://github.com/DaveSkender/Stock.Indicators/issues/947#issuecomment-1326004897) or was just being lazy when using that initializer in the one example he provided.  He only used it one of his examples, but skipped that initial incalculable period in others.  [Mathematically](https://github.com/DaveSkender/Stock.Indicators/issues/947#issuecomment-1326010495), skipping is more prudent (my bias).
