### ISSUE TITLE
Request : indicator support resistance

### ISSUE THREAD

**Issue by abcdamir2** [DaveSkender/Stock.Indicators#214]
Hi dave , thank you for the library you created and thank you for developing it . could you add '[support resistance](https://www.investopedia.com/trading/support-and-resistance-basics/)' indicator in your library ?
thanks a lot .

**Comment by DaveSkender** [comment]
Let's discuss.  Hopefully, we can get some ideas from others as well, on how to implement this.  Please go to #217 for discussion.

**Comment by DaveSkender** [comment]
Please continue the discussion at #217.  I'm closing this for now since it's too general to act on directly.  As we identify new indicators for the Support and Resistance category, we'll add them to the backlog; for example, we've recently implemented [Pivot Points](https://daveskender.github.io/Stock.Indicators/indicators/PivotPoints/#content) as a result of this discussion.
