### ISSUE TITLE
Possible wrong in the formula rsi indicator

### ISSUE THREAD

**Issue by morycom** [DaveSkender/Stock.Indicators#215]
Hi Dave
I think the formula used in the rsi indicator is wrong.
The rsi calculated for a particular day changes when the number of input data increases or decreases.
For example, if we use the price history of the last 20 trading days to calculate, the rsi calculated for the first day is different from when we use the price history of the last 30 trading days.
However, according to the rsi formula, it does not depend on the number of input data.
thanks a lot .

**Comment by DaveSkender** [comment]
Since [Relative Strength Index](https://daveskender.github.io/Stock.Indicators/indicators/Rsi/#content) uses a smoothing technique, there is essentially a "guess" value at the start of the historical quotes series that converges in accuracy over a warmup period.  As a result, yes, if you're using 20 vs 30 historical quotes for RSI(20), for example, you'd get *small* differences RSI values.  Because of this, we recommend you use 250 preceding historical quotes for the best accuracy.
