### ISSUE TITLE
SuperTrends is not correct?

### ISSUE THREAD

**Issue by l150039** [DaveSkender/Stock.Indicators#318]
Hi team.
I find SuperTrends result is not correct.
I tested it by "bitcoin 1 day candle 2017-2020" and compared with tradingview indicator result but not matched. (bollingerbands result is correct! good!)

can you check? thanks!

**Comment by DaveSkender** [comment]
Can you provide more information?

1. Link to the TradingView indicator
2. How are you using the library?  How much history, parameters, etc.

I’ll check it out.  As a side note, TradingView often uses user provided formulas, so it’s possible their formula is incorrect or that they made different assumptions.  Also, make sure you are using more than enough history, this indicator does have a warmup period where early vale’s in the time series will be less precise and should not be used.

**Comment by DaveSkender** [comment]
On my initial review of [the code](https://github.com/DaveSkender/Stock.Indicators/blob/master/indicators/SuperTrend/SuperTrend.cs), I'm not able to identify issues.  Currently, I do not have enough information to determine if there's an error in this library, the TradingView indicator, or if the comparison is based on the same historical quotes.

If anyone can provide information to clearly show an error in this library's formula, please do.  Otherwise, I'm going to assume that the TradingView implementation is errant or using "wicks" as the breakpoint, or that the provided historical quotes data is somehow different.

I'll leave this issue open for a while to elicit more feedback; however, will close it after a few days if we can't find a problem.

**Comment by l150039** [comment]
Hi Dave.

I test binance BTC-USDT (1day candle) Data. I will give you sample.
[BTCUSDT_1d_1610582399999_1610550000000.json.txt](https://github.com/DaveSkender/Stock.Indicators/files/5819925/BTCUSDT_1d_1610582399999_1610550000000.json.txt)

1. parsing data and try Indicator.GetSuperTrend.
(lookbackPeriod_supertrends = 10, multiplier_supertrends = 3)

2. and compare with binance tradingView (https://www.binance.com/en/trade/BTC_USDT)
![total](https://user-images.githubusercontent.com/77389426/104714105-22621280-5768-11eb-8120-49a9de3072f7.jpg)


Here is my result
![RES](https://user-images.githubusercontent.com/77389426/104714946-2e020900-5769-11eb-93b5-34649611e642.JPG)

and Binance sample
![1](https://user-images.githubusercontent.com/77389426/104714959-33f7ea00-5769-11eb-963b-8dc13dfc7116.jpg)
![2](https://user-images.githubusercontent.com/77389426/104714965-365a4400-5769-11eb-9ec6-507b41bf3cbc.jpg)

(not only 2 days but also every value is not same)

I tested "Indicator.GetSuperTrend" and "Indicator.GetBollingerBands" with binance BTCUSDT day value.
BollingerBands data is correct. it is same with binance tradingView's bollingerbands data, but supertrends is not (That is why I think my quote array is correct)

can you check it? Thanks!

**Comment by DaveSkender** [comment]
Is your parsed historical data identical to what is used in the Binance charts?  I'll take a look.  I suspect this has to do with different approaches to the "initial guess" and warmup period at the beginning of the series.  I'll take a look too in the next few days, but how does the data compare at the end of the history series?

Generally speaking, as I mention in the documentation, the first segment before the first reversal is unreliable and should be discarded.  I've been debating whether we should keep this data in the results or not as it can be confusing to users (see #306)

**Comment by DaveSkender** [comment]
At this point, I do believe the TradingView formula is wrong or is doing something unusual.  Here's my current hypothesis:

The formula for the lower band is `SuperTrend = MidPrice - Multiplier × ATR` where `MidPrice = (High+Low)/2`.  Given these values, directly from the Binance/TradingView chart (below), on Dec 6th, `SuperTrend = (19420.91+18902.88)/2 - 3 × 973.2082 = 16242.2704` where Binance/TradingView is showing an incorrect `16196.2300`.

![image](https://user-images.githubusercontent.com/8432125/104784946-626cc980-5757-11eb-9b67-bfa5f3bdb243.png)

**Comment by DaveSkender** [comment]
As a side note, I'm looking at Barcharts.com too, and see quite a bit of difference between Binance/TradingView and this library.  The Barcharts.com differences, I think, can be attributed to:

- different cryptocurrency prices, likely due to different daily cutoff times
- they appear to exclude weekend data in their charts and calculations
