### ISSUE TITLE
Williams Alligator

### ISSUE THREAD

**Issue by DaveSkender** [DaveSkender/Stock.Indicators#343]
Implement Williams Alligator
https://www.investopedia.com/articles/trading/072115/exploring-williams-alligator-indicator.asp

![image](https://user-images.githubusercontent.com/8432125/109362400-f2268d00-7858-11eb-84e5-15239ab0634b.png)

**Comment by tanjera** [comment]
I'd like to take a crack at this one. I looked at a couple of pages for calculations, and the best explanations I found are:

https://www.metatrader5.com/en/terminal/help/indicators/bw_indicators/alligator
https://www.metatrader5.com/en/terminal/help/indicators/trend_indicators/ma#smma

Since it uses SMMA (smoothed SMA), I may as well implement that as its own indicator. Sound okay?

**Comment by DaveSkender** [comment]
Go for it, but keep them separate PRs if you don't mind.

**Comment by tanjera** [comment]
No problem.

**Comment by tanjera** [comment]
Done implementing SMMA as a standalone indicator.-running performance tests on it now. Unit tests passed.  👍

I was considering whether it would be cleaner to reference an SmmaResults[] while calculating Alligator, or whether to just copy/paste the code. I agree with you that it'll probably perform better to copy/paste/modify the SMMA code rather than call the function- especially if I'll be doing any recalculating and/or additional iterating.

Now that I have a solid understanding of the SMMA, it shouldn't be too hard to tackle the Alligator... though I am still trying to understand the calculations on it. I'm attaching a screenshot from https://www.metatrader5.com/en/terminal/help/indicators/bw_indicators/alligator ... mind reading below and letting me know if you think my interpretation is correct?

<img width="758" alt="Capture" src="https://user-images.githubusercontent.com/543066/109369530-9e24a400-786a-11eb-9dc3-a812f4c86f98.png">

1) Their "formula" "SMMA (A, B, C)" where A is essentially a decimal[] of mid-point prices (they say "median" but the formula indicates mean), B is lookbackPeriod, ... **what is C**? Do they mean "shift to the future" as in "place it 3 days ahead in the result[] array"? That's the understanding I'm getting, which is probably why the charts all look like similar SMMA lines, transposed x days to the left/right.

Does it look like I'm understanding it properly?

**Comment by DaveSkender** [comment]
If you look at Bill Williams other indicators, some of this makes more sense.  In his Awesome Oscillator, median price = (H+L)/2

Not sure what C is yet, it may be just a [shift-right offset in period](https://www.forexfactory.com/attachment.php?attachmentid=1029464&d=1346336346).  I’m also now realizing that Alligator and Gator Oscillator are two different things, but probably both need to be in our results.

**Comment by tanjera** [comment]
Looking at the article you linked, it supports what I'm thinking that the 3 lines on the chart are just different SMMAs shifted to the right (future) by varying amounts. It makes sense that SMMAs of different N staggered differently would make the convergent and divergent features on a chart.

I also agree with you- it looks like Gator is an oscillator version, and Alligator travels on the chart along with the quotes.

**Comment by DaveSkender** [comment]
This is now available in version [1.10.0](https://github.com/DaveSkender/Stock.Indicators/releases/tag/1.10.0)
