### ISSUE TITLE
Python wrapper

### ISSUE THREAD

**Issue by DaveSkender** [DaveSkender/Stock.Indicators#394]
Add Python wrapper and publish as a community Wheel package to PyPI.
We're seeking Python contributors to lead an effort to build a version-synced parallel path Python wrapper for this library.

## Pull-Requests To Do

- [x] Add baseline wrapper with 1-2 indicators to prove our approach - @LeeDongGeon1996
- [x] Add initial unit tests to verify the implementation - @LeeDongGeon1996
- [x] Add packaging and unit testing to the build - @LeeDongGeon1996
- [ ] Add remaining indicators and unit tests - @LeeDongGeon1996
- [ ] Final sanity check and any needed refactoring
- [ ] Add general "Python support" documentation to expand the Guide (e.g. how to use the PyPI package)
- [ ] Update individual indicator documentation for Python usage
- [ ] Add deployment to package manager(s), deploy

**Comment by DaveSkender** [comment]
@LeeDongGeon1996 if you or anyone is interested in [contributing](https://daveskender.github.io/Stock.Indicators/docs/CONTRIBUTING.html) to this, let us know and we can start to discuss implementation details.  I haven't done a lot of research, so I'm unclear on whether we need to add any more C# code to make this easier.  I'm definitely here to help and contribute in those areas if needed.  I was thinking we put all the independent Python wrapper code in a new `/wraps/Python` folder in the repo.

My only ask is that we implement in small increments.  In other words, the first Pull Request should only include one or two indicators, without any documentation updates, and will be used to establish the baseline approach.

We can then figure out a strategy to get all the way to a published package that people can get from the public Python package managers.  I'll start a Pull Request To-Do list above to capture the sequence of increments and who's working on what parts to coordinate amongst collaborators.  Just announce here what piece you're picking up and I'll put your name next to it, then check it off when done.  Feedback appreciated.

**Comment by LeeDongGeon1996** [comment]
Hi, first of all, I'm happy to get a chance to contribute this project.
There are some topics I'd like to talk about:

 * **Why don't you separate the repo for C# and Python?**
   I think some of users using Python may want to look inside the project(library), but there is high probability of that they are only familiar with Python code and they might want to read only Python not a C#. Of course, most of important core implementation is written in C# and people should read C# code if they want to know how the module works exactly. But the options always should be there at least in my thought. That's why I think separating repo makes it easier to explore the code by language. please let me know your thought about this.

 * **Need to convert primitive type of C# and base class like `Qoute`, FIRST**
   When I analyzed your code to use it in Python, most of params are `IEnumerable<Qoute>` or `int`. and `Qoute` has several members which types are `Decimal` or `DateTime`. These types are using almost of `Indicator` funtions. So if we convert these first, then it would be much easier to convert other Indicator functions. So I think this should be prior with "*Add baseline wrapper with 1-2 indicators to prove our approach*" among TO-DO list.

Waiting for your reply :)

**Comment by DaveSkender** [comment]
> * **Why don't you separate the repo for C# and Python?**
>   I think some of users using Python may want to look inside the project(library), but there is high probability of that they are only familiar with Python code and they might want to read only Python not a C#. Of course, most of important core implementation is written in C# and people should read C# code if they want to know how the module works exactly. But the options always should be there at least in my thought. That's why I think separating repo makes it easier to explore the code by language. please let me know your thought about this.

I don't have a strong opinion on this and see the pros and cons of both approaches.  My initial thought was that it would be easier to maintain version and documentation parity -- to build and deploy simultaneously -- if the code were in the same repo.  If I were wrapping someone else's code, I'd definitely do a separate repo.  In our case, we're mostly just putting a "cover" on existing code, so to me, it's the same project with extra features.

> * **Need to convert primitive type of C# and base class like `Qoute`, FIRST**
>   When I analyzed your code to use it in Python, most of params are `IEnumerable<Qoute>` or `int`. and `Qoute` has several members which types are `Decimal` or `DateTime`. These types are being used  in almost of `Indicator` funtions. So if we convert these first, then it would be much easier to convert other Indicator functions. So I think this should be prior to others while doing "_Add baseline wrapper with 1-2 indicators to prove our approach_" among TO-DO list.

No arguments here, sounds like a good idea.  I'll add your name to that first one; and if you end up doing it in two smaller PRs, that's okay too.  Are you aware of any parts of this that might need to be done in the C# DLL?

**Comment by LeeDongGeon1996** [comment]
* **~~Why don't you separate the repo for C# and Python?~~**
 I get it and agree with your opinion. As you told,  `/wraps/python` can be a landing page for Python users. That would be better than separating repo.

* **Need to convert primitive type of C# and base class like Quote, FIRST**
Okay. Then I will start from this(convert `Decimal`, `DateTime` and so on). And I don't have nothing that might have to be done in C# DLL at least until now. Actually I'm thinking of that there would be no difficulty after converting primitive type and base class(`Qoute`) because you've already done core implementation. But cannot be sure the future haha
**My Plan** is finishing it until this Friday. Is it okay to you? If you want to process more quickly, please tell me.

And, there is one more thing to discuss:
* **Naming Rule**
There are many Naming Rules being used in Python as describing in [PEP 8](https://www.python.org/dev/peps/pep-0008/#naming-conventions). According to PEP 8, you've been using "*CapitalizedWords*", but I'm thinking of using "*lower_case_with_underscores*" which is used in [Pandas](https://pandas.pydata.org/) library. Pandas is, as you already know, the most popular library for data analysis in Python world. That's why I'm using Padas as an example now. How do you think?
  *  `GetSma()` would be `get_sma()`

**Comment by LeeDongGeon1996** [comment]
Yes, That's right. We should widely accepted Naming Rules. That's why I refer the [PEP 8](https://www.python.org/dev/peps/pep-0008/#naming-conventions). PEP(Python Enhancement Proposals) is official Python documentation in [Python Developer's Guide](https://www.python.org/dev/). 
It says:
> The naming conventions of Python's library are a bit of a mess, so we'll never get this completely consistent -- nevertheless, here are the currently recommended naming standards.

And its recommendation for [function and variable names](https://www.python.org/dev/peps/pep-0008/#function-and-variable-names):
> Function names should be lowercase, with words separated by underscores as necessary to improve readability.

This style is official recommendation and also accepted in Pandas. So I think we should go with it.

**Comment by LeeDongGeon1996** [comment]
If you review #397, I'm sure you will find that making wrapper for the rest part is just "typing". 
What will be out next step?

**Comment by DaveSkender** [comment]
Let's get through the code review of #397 and merge processes, then move onto adding some basic unit tests that verify that `get_sma` runs and produces the quantity and has all expected values.  Might be good to spot check results values using the same unit test parameters we use in the C# DLL, just to make sure the needed precision is still there.

**Comment by LeeDongGeon1996** [comment]
* **Unit Test**
 About the unit test, we need to use `GetHistoryFromFeed()`. In Python, I implemented own `get_history_from_feed()` using [FinanceDataReader](https://github.com/FinanceData/FinanceDataReader). Is there any reason you don't support this function? And I think we need to use same `GetHistoryFromFeed()` for unit test.

**Comment by DaveSkender** [comment]
For unit tests, we need to use a static set of mock data so the results are repeatable, so we're not using `GetHistoryFromFeed()` at all in the library to fetch live data -- that's just a placeholder example of what someone might have in their own code to get quote history.

The Excel `history.xlsx` spreadsheet in the `tests/indicators/test data` folder contains all that static data.  The related `.cs` files are used to compose it for use in the C# unit tests.  In other words, we have a `HistoryTestData.Get()` function that is basically a mocking tool that would represent `GetHistoryFromFeed()`.

For this Python wrapper, we can probably get away with just running the Standard test data and test cases.  I expect we'll need to do either 1) an equivalent fetch of the mock data in Python, or 2) rig and call the test DLL so you can call it in Python to get the data.  It might be simpler to do #1 and avoid the whole entanglement with another C# DLL.

**Comment by LeeDongGeon1996** [comment]
Now, then I would like to go to the next step, "*Add initial unit tests to verify the implementation*", making unit test for `get_sma()` and `get_sma_extended()`

**Comment by LeeDongGeon1996** [comment]
What's going to be the next?  "*Add packaging and unit testing to the build*"??

**Comment by DaveSkender** [comment]
Yes, I think it makes sense to run a parallel process in the build to cover the Python parts, both running/publishing unit tests + packaging/saving artifacts for publishing to PyPI.  We’ll do actual publish to PyPI in a separate process, later.

The build script for Azure DevOps is in the .github folder.  You’ll have to create a draft PR to verify that it’s working okay.

**Comment by LeeDongGeon1996** [comment]
Of course! I'll get in on this and let you know if I need you to help.

**Comment by LeeDongGeon1996** [comment]
Let's go to the next step, `Add remaining indicators and unit tests`.🚀

**Comment by LeeDongGeon1996** [comment]
@DaveSkender , Hi, I'm really really busy until next weekend. I'm still be here. 😂😭

**Comment by DaveSkender** [comment]
@LeeDongGeon1996 I’m converting this issue to a discussion.  We can still use it to track progress.
