### ISSUE TITLE
optional user selection of OHLC input to indicators

### ISSUE THREAD

**Issue by moslem7026** [DaveSkender/Stock.Indicators#439]
calculating output of indicator can be depend to Open, High, Low or close .
at this moment calculating indicators is on "Close" default . and it is not possible to calculate in other mode.

for example `GetRSI` method always calculated on close of candles. i see that it has implemented `ConvertToBasic` method and this one choose close defualt .

why not have input parameter `source` to choose ConvertToBasic parameter

**Comment by DaveSkender** [comment]
In theory, we could have a parameter to specify which OHLC element to use for _some_ indicators.  I see other systems doing this and in many cases they are deviating from the original formula (e.g by replacing True Price with C or any custom OHLC variant).

For me, it's a value vs complexity tradeoff.  My view is that it adds complexity with little or no value => is RSI based on H instead of C a better option, or just a curiosity?

**Comment by thomasd3** [comment]
an option could be to have the indicator taking streams of values that could be built by scanning the candles. For example an EMA just needs a price; so if you could have candles -> streambuilder -> ema you'd be able to use the data you want, including non candle sources such as a straight source or prices.
right now the indicators imply that you have all the candle data available, but it is not useful in many cases

**Comment by DaveSkender** [comment]
Generally speaking, I do plan on looking at the streaming use case in the next major version.  With that said, it's not as simple as adding one incremental price in many of the indicators since they do actually rely on more than one point for calculations (see #396).  For your example, EMA uses the prior period EMA and is primed with SMA over a lookback period.

**Comment by thomasd3** [comment]
yes, I understand the need for history, but ultimately the SMA/EMA only need a decimal array, they don't need the rest of the candle. So if I could do something like:
- candle -> close array -> ema, or
- candle -> (high-low)/2 + low -> ema
etc
it would give more flexibility; the same can be done with functions that require more than one stream. Ultimately, it is really about inserting an intermediate layer.

**Comment by DaveSkender** [comment]
Well, the problem is that the data almost always comes in the form of a standard OHLCV candle quote, so you'd have to decompose it yourself anyway before sending it in = extra work for the developer.  The basic design choice for this library is to make it easy to use.  Requiring the developer to do a lot of prerequisite data transformation work outside the library in this way is not appealing to me.  I have a lot of experience with array-based library packages, like TA-Lib.  It was a mountain of work both before and after using the library to put and get the data back into a usable format.  Didn't like it.

**Comment by DaveSkender** [comment]
With that said, it a bit of a hack, but you could always recompose the Quote to put whatever value you want in the Close property (EMA example), if you wanted something else.

**Comment by DaveSkender** [comment]
I'll not be adding an option to use any custom OHLCV element for formulas in v1; however, I think some of these options might be partly available in v2 (see #218) with the ability to use incremental calculations.  As a design choice, we're also intentionally not using an array-based model, like the 30-year old TA-Lib.
