### ISSUE TITLE
Returning objects should not hide the implementation

### ISSUE THREAD

**Issue by dtila** [DaveSkender/Stock.Indicators#489]
The static methods on the Indicator class, all of them return IEnumerable. While IEnumerable make sense where you really have an enumeration, it does not make sense where functions internally create a list, and then they hide the implementation to an IEnumerable.

It is a best practice to accept parameters with as less methods you need (in this case you only need an IEnumerable) and to return the most specific object (in this case should be a list and not IEnumerable). One of these examples is the RSI calculation objects.

**Comment by DaveSkender** [comment]
I was sorta under the impression that the [Common Type System](https://docs.microsoft.com/en-us/dotnet/standard/base-types/common-type-system) standards preferred `IEnumerable` over `List`, but I may have been thinking that applies to both inputs and outputs -- I certainly could be wrong.  I can probably learn something new here.

Are you referring to the result classes, e.g. `IEnumerable<RsiResult>` output from `GetRsi`?

**Comment by DaveSkender** [comment]
I'm reading about this a bit more.  For public methods, I can probably return `IList<T>` instead of `IEnumerable<T>`, which seems to be more aligned with what you're saying.  Thoughts?

**Comment by dtila** [comment]
Yes, your point is exactly what I was referring. Generally the best practice is to have for input parameters, the least specific (like IEnumerable) and for output parameters, the most specific (to not hide implementation).

Also I had a look to the CA1002 rule, and I can not understand the reasons behind this rule. Per the rule, using List it is recommended for performance. This would mean that you can disable this rule, if you writing performance code :) ?

Back to the suggestion to use a IList, it is definitely better than using IEnumerable. However, IList it is implemented by the List and Array classes, and using the interface methods, they are technically slower than using a class (like List). This will violate the CA1002 rule definitely, so I think it is up to the designer what is the KPI you want to follow.

@DaveSkender What are your thoughts to this?

**Comment by DaveSkender** [comment]
I’ve been reading more about this and to me it looks like one of those design choices where there is no clear correct answer; rather, it’s best to evaluate on a case by case basis — despite the existence of strong opinions one way or the other.

For our internal/private methods, listed above, the internal caller almost always needs the functions of the List for further processing, so it makes sense to return in that format, and there is no concern about breaking code as it’s all encapsulated in the library.

For our external methods, I’ll probably just leave them as IEnumerable results for now since it 1) reduces the risk of introducing breaking code to external callers, 2) probably persists List features when callers need to do .ToList() with only negligible performance cost, and also 3) there’s no obvious need to return a List or IList.  With that said, I’m still trying to fully evaluate benefit and cost.

**Comment by dtila** [comment]
Based on my exceprience, I prefer to expose specific types for output, than hiding the implementation. I would go on this since it has more gains. 

Causing breaking changes has a low probability to happen, since everymethod that works on IEnumerable, will work on Lists also. 

In my personal case, I had to create another list to merge more results. If it would return a list, it would be much easier to go thought each element index.

Also, another benefit would be in case you want to return a struct and not a class. Since creating a List with structs, would allocate the content that the structure will have, and not only the reference pointer to the memory. In this case the allocation will be bigger and to be honest this is what I was doing. 

For high performance code, these tricks help a lot, but you are owner so it is up to you to decide ;)

**Comment by DaveSkender** [comment]
Well, I do want external callers to get the best performance both in and with use cases for the library, but also balance overall usability.  For example, I've had suggestions to make the library entirely based on Arrays so it would perform better; however, while true for the library speed, all that does is make it harder to use and to move the performance hit and needed work to other external processes (data transform before/after becomes someone else's problem).

I do appreciate hearing about your use cases, that's very helpful.  Since your argument for returning `List` is primarily about performance, I'm curious to see if an `IEnumerable` that was originally created from `List` is measurably slower when an external caller has to use `.ToList()` to get it back into that format.  I can test this.  I suspect that it's extremely small.  I'll check it out this weekend.

**Comment by DaveSkender** [comment]
In doing some performance tests to compare these options, I have three test scernarios with a regular (502 bars) and longer (5285 bars) set of historical quotes:

```csharp
// scenario 1: normal, return IEnumerable
IEnumerable<StochResult> r = h.GetStoch();
return r;

// scenario 2: return IEnumerable and convert ToList()
List<StochResult> r = h.GetStoch().ToList();
return r;

// scenario 3: return generic List
List<StochResult> r = h.GetStochList();
return r;
```
I can't explain these results, but I'm not seeing any notable difference between these scenarios.  Any differences I see are within normal variances between test runs.  I ran it three times to show this variance, but each run is a statistically significant set.
 
``` ini
BenchmarkDotNet=v0.13.0, OS=Windows 10.0.19043.1110 (21H1/May2021Update)
Intel Core i7-7700HQ CPU 2.80GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
.NET SDK=5.0.302

|        Method |       Mean |    Error |   StdDev |
|-------------- |-----------:|---------:|---------:|
|     Scenario1 |   416.4 μs |  2.34 μs |  2.19 μs |
|     Scenario2 |   413.3 μs |  1.73 μs |  1.44 μs |
|     Scenario3 |   416.8 μs |  2.06 μs |  1.72 μs |
| Scenario1Long | 4,956.9 μs | 32.84 μs | 30.71 μs |
| Scenario2Long | 4,827.2 μs | 28.13 μs | 26.31 μs |
| Scenario3Long | 4,887.9 μs | 34.03 μs | 30.16 μs |

|        Method |       Mean |    Error |   StdDev |
|-------------- |-----------:|---------:|---------:|
|     Scenario1 |   413.9 μs |  2.82 μs |  2.64 μs |
|     Scenario2 |   416.1 μs |  3.16 μs |  2.80 μs |
|     Scenario3 |   412.2 μs |  1.49 μs |  1.39 μs |
| Scenario1Long | 4,952.3 μs | 28.48 μs | 25.24 μs |
| Scenario2Long | 4,882.1 μs | 43.97 μs | 38.98 μs |
| Scenario3Long | 4,904.3 μs | 33.93 μs | 28.33 μs |

|        Method |       Mean |    Error |   StdDev |
|-------------- |-----------:|---------:|---------:|
|     Scenario1 |   413.4 μs |  2.05 μs |  1.81 μs |
|     Scenario2 |   415.8 μs |  2.55 μs |  2.39 μs |
|     Scenario3 |   415.4 μs |  2.08 μs |  1.95 μs |
| Scenario1Long | 4,875.3 μs | 35.60 μs | 33.30 μs |
| Scenario2Long | 4,881.0 μs | 57.16 μs | 47.73 μs |
| Scenario3Long | 4,924.4 μs | 39.36 μs | 36.81 μs |
```

**Comment by dtila** [comment]
The improvement would be higher if the RsiResult would be a struct and not a class. Hence with the current structure to have a result base would not be possible, but using the IResult would be possible.

I am not sure what is the purpose of the ResultBase, but if having a contract for all the result, using just the interface would have helped alot. 

Going back to our problem, I not so surprised by the result, since in the list there are only references and not the result themselves. The performance problem persists not only to the RSI calculation, but also on the code that is using the RSI. Using the IEnumerable along with the class, is causing a performance penalty. I could say this would decrease the execution time by 4x.

My point is that the performance penalty measurement it is incomplete, and from a project where you are dealing with a lot of data, it is definetelly a win.

I am currently on a project that involves massive data calculation, and I would definetelly make a measurement after I finish the POC, I will come to this issue with some measurements :)

**Comment by DaveSkender** [comment]
Early in development I thought there would be more commonality between result classes, hence the derived base class.  Not mandatory.

But yah, let’s keep poking at this.  I’ll be interested to see if there’s something reasonable we can do for heavy data usage cases.  Look forward to your measurements.

**Comment by DaveSkender** [comment]
Without more information that indicates a problem or measurable improvement, there is nothing more to do on this issue.  I’ll reopen if needed.
