### ISSUE TITLE
StochasticRsi dos not have smoothK and smoothD

### ISSUE THREAD

**Issue by morycom** [DaveSkender/Stock.Indicators#64]
hi
1-Stochastic Rsi usually return two value but your function return single value.
2- How to change %k and %d parameters in Stochastic Rsi? 
Thanks

**Comment by DaveSkender** [comment]
I suspect you need to use the [Stochastic Oscillator](https://daveskender.github.io/Stock.Indicators/Indicators/Stochastic) indicator `GetStoch(h,period,k,d)` instead of the [Stochastic RSI](https://daveskender.github.io/Stock.Indicators/Indicators/StochasticRsi) oscillator (GetStochRsi(h,period).  They are similar and often confused with each other.

If you are seeing and industry standard second line on Stochastic RSI, please send me some references and I'll review and add to the library.

**Comment by mosta91** [comment]
In the below link, you can see that Stoch RSI has four inputs and 2 outputs but your function have 2 input and only one output.
https://www.tradingview.com/support/solutions/43000502333-stochastic-rsi-stoch-rsi/
How can i change this function to achieve the result similar to above link.

**Comment by DaveSkender** [comment]
Ah, I see what they did there.  Most implementations and the [original definition](https://www.investopedia.com/terms/s/stochrsi.asp) of Stochastic RSI use the Fast Stochastic variant and don't provide a signal line so there'd be no need for those extra parameters.  The version in your link allows for that additional customization.  I like it.  Adding in AB#650

**Comment by DaveSkender** [comment]
This recommendation enhancement was implemented in v0.8.3 and is now available.  Thank you for your feedback.

**Comment by morycom** [comment]
Thanks
