### ISSUE TITLE
Detrended Price Oscillator (DPO) has missing Values depending on the offset / Lookback

### ISSUE THREAD

**Issue by mexxBf** [DaveSkender/Stock.Indicators#654]
Hi,

I'm trying to use the DPO for my Backtests and observed some strange behavior. Its missing the latest Values depending on the lookback. 

Lets say I have a lookback of 21, then the list is missing the latest  10 values.

its calculated like this:
`int offset = lookbackPeriods / 2 + 1;`

but then:

```
if (i >= lookbackPeriods - offset - 1 && i < size - offset)
                {
                    SmaResult s = sma[i + offset];
                    r.Sma = s.Sma;
                    r.Dpo = q.Close - s.Sma;
                }
```

It is trying to add the offset to the SMA  "i"  (SmaResult s = sma[i + offset];) instead of subtracting it. At least if I'm not wrong, or missing something.

Thank you :)

**Comment by DaveSkender** [comment]
> Its missing the latest Values depending on the lookback.

I'll have to review the formula again to refresh my memory; however, the [DPO documentation](https://daveskender.github.io/Stock.Indicators/indicators/Dpo/#content) does indicate that the last `N/2+1` values are `null` because they cannot be calculated.  This may just be an inherent normal behavior of that indicator.

**Comment by DaveSkender** [comment]
StockCharts.com has [a good description of the formula](https://school.stockcharts.com/doku.php?id=technical_indicators:detrended_price_osci) and what to expect.

**Comment by DaveSkender** [comment]
I think the mental math is confusing, but the SMA for today is an offset backwards of a future SMA, so you have to "lookup" the future SMA for today.  It's like a double negative, hard to read.  I'll take a closer look when I have more time to double-check.  Thanks for mentioning, I like to review these again from time to time when questions arise.

**Comment by mexxBf** [comment]
This is how I would solve this:

```
if (sma[i].Sma == null || sma[i - offset].Sma == null || i - offset < 0 ) continue;
var s = sma[i - offset];
```

I personaly think its easier to read, but I guess its not everyones taste :-)


"i" is the current list position. Minus offset to get the (i - offset) position of the sma. so we are looking at "today" minus 10 e.g.

After that it compares the current close to the offset Sma. 


Maybe its just confusing how the list of quotes are ordered?  

Btw: 

The Tradingview implementation looks like this:

`dpo = isCentered ? close[barsback] - ma : close - ma[barsback]`


Thank you for all your work 🥇

**Comment by DaveSkender** [comment]
`(i-offset)` would shift the SMA into the future since our arrays are in chronological order, right?

TradingView tends to have some unusual community contributions.  I can't speak for the "creative" things they may do.  We're using the consistently same definition as these [more] reputable sources:

- StochCharts.com
- Investopedia
- Wikipedia

**Comment by DaveSkender** [comment]
For comparison:

![image](https://user-images.githubusercontent.com/8432125/145112617-49477206-d3b8-49eb-bbb5-5accbe57adc5.png)

![image](https://user-images.githubusercontent.com/8432125/145112595-e1d013e9-052a-4ac5-9955-d8c035ae5a4b.png)

**Comment by mexxBf** [comment]
I guess I can put some light on my "misinterpretation" of the Indicator :) 

I compared your correctly implemented "centered" implementation to the by default not centered version of tradingview.

I am sorry, I didn't knew there was another "way" of calculating the DPO. 

But maybe this  "non centered" version would be a nice feature for the DPO :) 

Thank you once more!

**Comment by DaveSkender** [comment]
> I didn't knew there was another "way" of calculating the DPO.

Me neither!  I've not seen that before.  Community contributions on TV tend to have some creative interpretations or additions, not all make sense and are often not part of the original definition.  I tend to stick with the original definitions from the original source but have made a few exceptions.  I generally prefer to not add things just because someone else did it, especially if I don't understand its added value, just to keep things simpler.
