### ISSUE TITLE
Add Black Flag indicator

### ISSUE THREAD

**Issue by codebeaulieu** [DaveSkender/Stock.Indicators#715]
I would love to see the addition of the black flag indicator also known as "swing arm".

here is an example in think script:
https://usethinkscript.com/threads/blackflag-fts-swingarm-trend-indicator-using-atrtrailing-stop-and-fibonacci-retracements.2486/

and here is an example in pine script:
https://www.tradingview.com/script/Dxc0Pi3n-SwingArm-ATR-Trend-Indicator/

Example:
<img width="1081" alt="Screen Shot 2022-02-16 at 11 09 55 AM" src="https://user-images.githubusercontent.com/9411281/154307166-f35bbc0d-8eb7-4711-befa-ea3ea1ef0308.png">

**Comment by DaveSkender** [comment]
This has a lot of the same themes as [SuperTrend](https://daveskender.github.io/Stock.Indicators/indicators/SuperTrend/#content).  I'll take a closer look when I get a chance.

**Comment by DaveSkender** [comment]
While this one is interesting, I think this falls into the realm of random community indicators instead of a time tested standard.  It would make a good [custom indicator](https://dotnet.stockindicators.dev/custom-indicators/#content) that I’d encourage others to build and share in [our discussions](https://github.com/DaveSkender/Stock.Indicators/discussions) board.
