### ISSUE TITLE
GPU Trading Indicators

### ISSUE THREAD

**Issue by kiranmaya** [DaveSkender/Stock.Indicators#804]
Hi,
I'm from India, and here lots of people fight for orders, 
I recently converted a few indicators to support runtime trading calculating based on the last candle, and had some excellent results in mock trading, but was unable to catch orders in time. will you write one GPU Based indicator as an example? For high-frequency methods, GPU is best for batch stock symbols .currently my CPU thread is taking 0.8ms for two indicators-based logic, I read that it will be done by nano seconds with multiple stocks.
Thanks
kiran

**Comment by DaveSkender** [comment]
GPU seems to be a trend right now.  I’d have to see a real world HFT/GPU example before considering updates to our library to support it.

I also need to get to v2 features in our library, to better support an incremental streaming data model.

**Comment by DaveSkender** [comment]
That's a really cool concept, pre-processing likely incremental scenarios for the next tick so they're more readily available.  I'm very much interested and and have been planning to work on the incremental streaming model in the [next major version](https://github.com/DaveSkender/Stock.Indicators/discussions/218) (because there will be notable breaking changes).

With that said, I also have a few more basic things to finish for v1 before I can move on to address this use case.

Also, before I jump into the world of building for GPU, I'm going to need to recruit some GPU experts to help shorten our learning and to demonstrate, with examples, how it is implemented properly.

Know anyone who might want to contribute to our open-source project to help things move a little faster?

**Comment by DaveSkender** [comment]
In doing some reading, GPU compatibility for indicators will need to be an entirely new library because it requires unique programming concepts that may not work well for people who can’t or don’t want to use a GPU.

I’ll keep this in mind for a new project, but for now, please follow [our discussion](https://github.com/DaveSkender/Stock.Indicators/discussions/765) as we learn how to approach this model.
