### ISSUE TITLE
add True Range (separately from Average True Range)

### ISSUE THREAD

**Issue by barisertekin** [DaveSkender/Stock.Indicators#844]
Hi,

Can smoothing be added to the ATR indicator like in Tradingview?
We need RMA smoothing.
Screenshot attached.

Thank you.

![ATR](https://user-images.githubusercontent.com/7264947/178005341-f5fee108-44ec-4549-b369-b68e267ab60c.png)
![RMA](https://user-images.githubusercontent.com/7264947/178005767-4ea9f16d-0539-4230-854f-3b206e9cdcfa.png)
![RMA2](https://user-images.githubusercontent.com/7264947/178006530-4bad235d-78d3-47a5-b14c-6f80d0642e82.png)

**Comment by Erdogan34** [comment]
We need it too if its possible!

**Comment by barisertekin** [comment]
You are absolutely right, but I couldn't find it before because the name was different.
Running Moving Average (RMA) = GetSmma

Thank you.

**Comment by DaveSkender** [comment]
I'm looking at the code for `.GetAtr(..)` and I think its default moving average type is just SMMA/RMA, so you'd only need the proposed chaining above if you wanted some other type of moving average.

I'm reopening, because we don't have `.GetTr()` yet; I need to break that out so it's separate.  I may just add it as a `.Use(CandlePart.TR)` option; not sure yet.  True Range is a very basic quote transform.

**Comment by DaveSkender** [comment]
> I couldn't find it before because the name was different. Running Moving Average (RMA) = GetSmma

These things often have multiple names.  I could put overrides in with `.GetRma(..)`, but for now I've just added aliases in the [documentation site list](https://daveskender.github.io/Stock.Indicators/indicators/#moving-average).

**Comment by DaveSkender** [comment]
This is now available in v2.1.0
